services:
    db:
        image: postgres:17
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}

    web:
        build: .
        container_name: web
        depends_on:
            - db
            - redis
        volumes:
            - ./orgchat:/app/orgchat
            - ./static:/app/staticfiles
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '8000:8000'
            - '8001:8001'

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '8080:8080'
        depends_on:
            - web
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
        networks:
            - default

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'

volumes:
    postgres_data:
